Desktop: Enable 'Alt+Left/Right' for history navigation.
lbryio/lbry-desktop pull request #5203
Opened 2020-12-17 16:01 UTC by infinite-persistence

## Why
- Consistent behavior across Web and Desktop.

2020-12-21 17:13 UTC, seanyesmunt requested changes
Looks good. Just one comment

2020-12-21 17:13 UTC, seanyesmunt commented on ui/effects/use-history-nav.js
> +      if (e.altKey && !e.ctrlKey && !e.shiftKey) {
This should use `cmd` for mac instead of `alt`

2020-12-21 17:28 UTC, infinite-persistence commented
`Update`
- Rebased
-  Changed
```
      if (e.altKey && !e.ctrlKey && !e.shiftKey) {
```
to
```
      if ((e.metaKey || e.altKey) && !e.ctrlKey && !e.shiftKey) {
```

2020-12-30 19:32 UTC, seanyesmunt approved these changes

2020-12-30 19:55 UTC, merged