WIP Floating player on scroll
lbryio/lbry-desktop pull request #5544
Opened 2021-02-18 15:06 UTC by kauffj

see #4932 for context, @Ruk33 is looking for feedback on this

2021-02-18 20:21 UTC, DispatchCommit requested changes
Listening to the scroll event can lead to performance issues.

At the minimum, the event listener should be a passive event listener:
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

But the *best* solution would be to use an intersection observer instead:
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

Intersection observers is what bitwave uses to popout it's player on scroll:

https://github.com/bitwave-tv/bitwave/blob/40dc640fde12cf26aa320006ec259d4e66aeb6dc/pages/_watch/index.vue#L21-L30

https://github.com/bitwave-tv/bitwave/blob/40dc640fde12cf26aa320006ec259d4e66aeb6dc/pages/_watch/index.vue#L376-L378

2021-02-18 20:23 UTC, DispatchCommit commented on ui/page/file/view.jsx
> +    window.addEventListener('scroll', onScroll);
https://developers.google.com/web/updates/2016/06/passive-event-listeners

2021-03-01 20:11 UTC, kauffj commented
@Ruk33 do you want to come back to this?

2021-03-02 21:54 UTC, Ruk33 commented
Hello @kauffj sure, I was finishing the release date input now I'll continue with this one. Thanks for following up!

2021-03-19 15:12 UTC, seanyesmunt commented
@Ruk33 I'm going to close this one while I am cleaning up the repo a bit. This would be a great feature to have though! Feel free to re-open this PR when you start working on it again.

2021-03-19 15:12 UTC, closed without merging