Restore video loading circle
lbryio/lbry-desktop pull request #5570
Opened 2021-02-23 08:53 UTC by infinite-persistence

## Issue
Closes #5554[: Video: loading circle sometimes does not appear until 2nd click](https://github.com/lbryio/lbry-desktop/issues/5554)

## What's happening
videojs behavior:
(a) A `src` change makes the Play button re-appear.
(b) An `onPlay` (or `play()`) makes the button go away.

Due to the `m3u8` header async fetch (i.e. return is potentially delayed), the initial `onPlay` (which cleared the button) that happened after user clicked Play gets negated by a potentially-delayed `src` change.  

![image](https://user-images.githubusercontent.com/64950861/108820038-92c94280-75f6-11eb-8141-da544074d703.png)

## Approach
I believe in our use case, a change in `src` always means "change src and resume play". A `src` change always comes from a Play action, and we don't pause (don't need to anyway) the player during the change.

So, hiding the button after `src` is changed seems reasonable.

## New behavior
We now see the spinning loading circle when video is loading, as it was originally.

## Aside
Is there a non-async alternative to the header fetching?  Seems to be the root of many problems.  When the fetch is fast, we avoid the double `onPlay`
![image](https://user-images.githubusercontent.com/64950861/108820724-927d7700-75f7-11eb-8f7d-4336e3fe8d7a.png)

2021-03-01 19:34 UTC, DispatchCommit commented
I've been debating back and forth on how to handle and fix issues related to that async fetch call and haven't decided if it makes more sense to take that out of the internals and simply do the fetch *before* updating the `src` for the player or perform the check in the player code.

I think it makes more sense to separate the concerns and responsibilities and only update `src` after the fetch has completed in a parent component - then just pass `src` and `type` to the player directly so it only ever has to worry about standard video.js setup and event flows.

2021-03-01 19:54 UTC, DispatchCommit requested changes
PR resolves issue with play button appearing while async fetch is waiting to return - however due to the change hiding the play button `onPlayerReady`, if the player is not allowed to autoplay, the play button will *not* appear.

Example: notice the play button appears on the left, but not the right. Neither player is in the `play` state currently.

![image](https://user-images.githubusercontent.com/45262335/109550363-08646100-7a84-11eb-9bd6-c52152cae87b.png)

Left is production, right is this PR. I have disabled all autoplaying on this browser, and as a result, the play button will not appear -- yet the player is currently paused (stopped).

I think this behavior further reinforces the idea that the fetch should be done prior as there are many edge-case issues with async fetch'ing internally.

I'm not sure it makes sense to address this issue within the component this way. You could workaround this by hidding the play button until after the fetch, then checking after the fetch if the player has started to show or hide the button, but that also circles back to the need to fix how the player autoplays.

2021-03-01 20:00 UTC, DispatchCommit commented
Ideally we would want to have this loading indicator show until the pre-fetch is completed I think...

![image](https://user-images.githubusercontent.com/45262335/109551686-b9b7c680-7a85-11eb-92ce-77d775a3180a.png)

2021-03-02 02:04 UTC, infinite-persistence commented
> _Ideally we would want to have this loading indicator show until the pre-fetch is completed I think..._

Yup, that is what the PR is trying to achieve -- it should show the loading screen above, followed by buffering loading circle, then play -- except that I missed out on the browser-level autoplay=off scenario,

I agree that the async fetch is the actual root of many issues.  If a fix is coming up soon, we don't need this PR;  else, I think having this workaround is better than today's version (the change is simple to revert).  Having to guess whether I did click play or not is getting annoying :)

----

`Update`
- Handle the case of the player being paused externally.

2021-03-02 08:54 UTC, infinite-persistence commented
`Update`
- Squashed commits and added comments in the code to ease the revert process during the upcoming re-architecture.

2021-03-04 18:21 UTC, DispatchCommit commented
Can #5535 be closed in favor of this since this PR contains the changes from that PR as well?

2021-03-04 19:00 UTC, infinite-persistence commented
> _Can #5535 be closed in favor of this since this PR contains the changes from that PR as well?_

@DispatchCommit, sorry, I ended up force-pushing the wrong branch and made it identical to 5535. Both PRs should be addressing different things.

`Update`
- Corrected the branch for this PR.

2021-03-05 22:28 UTC, DispatchCommit approved these changes
"better than nothing"

will properly address and fix in a future refactor of the pre-fetch

2021-03-08 18:28 UTC, merged