Add filtering on notifications page - 5193
lbryio/lbry-desktop pull request #5624
Opened 2021-03-05 04:14 UTC by infinite-persistence

## Issue
Closes #5193[ Add filtering on notifications page](https://github.com/lbryio/lbry-desktop/issues/5193)

## Notes
- Add a combo box, and simply filter out the notifications based on the combo box value.
- Selection state is persistent, but reset to All if there are unread ones when entering the page.
- Tell the user that "no notifications" could be due to the filter.
- Used "Followers" instead of "Subscribers". 
- Re-used the same CSS as "claim search filter".

![image](https://user-images.githubusercontent.com/64950861/110066343-2e537380-7dac-11eb-88be-f58ce74d03e5.png)

2021-03-09 20:27 UTC, seanyesmunt requested changes
Please move the title outside of the card, similar to how the `/$/uploads` page looks. Then move the `select` to the left of the "mark all as read" button

2021-03-10 04:22 UTC, infinite-persistence commented
### Update
- Moved the title and actions out, similar to Uploads Page.
    -  Unlike the Uploads Page, I think we would want to display the action buttons on mobile as well (or at least show "Mark all as read").  With that, `claim-list__alt-controls--wrap` was added. Hopefully the mobile look doesn't deviate from style too much.

<details>
  <summary>Screenshots</summary>

## Normal:
![image](https://user-images.githubusercontent.com/64950861/110575934-bf569000-819a-11eb-8410-daee0da22347.png)

## Medium:
![image](https://user-images.githubusercontent.com/64950861/110575949-c8476180-819a-11eb-88c2-9807ee4c4242.png)

## Small:
![image](https://user-images.githubusercontent.com/64950861/110575959-d1d0c980-819a-11eb-864b-214eec9ed3a1.png)
</details>

2021-03-10 21:50 UTC, seanyesmunt commented
Hmm. This might need some more UI work to deal with the smaller screens. I'll spend some time thinking more about how this should be displayed. Thanks for postign the screenshots.

2021-03-12 13:51 UTC, seanyesmunt approved these changes

2021-03-12 13:51 UTC, merged