Batch-resolves channel page query
lbryio/lbry-desktop pull request #5625
Opened 2021-03-05 07:17 UTC by infinite-persistence

## Issue
Closes #5597[ batch resolves on channel search page](https://github.com/lbryio/lbry-desktop/issues/5597)

## Changes
Do a batch-resolve immediate after getting the results and before setting the result variable, as the latter would result in the Claim* components resolving individually.

## Notes
I enabled `returnCachedClaims` -- I assumed that's a reasonable thing to do. I don't see other places use it, though, so highlighting it here.

2021-03-05 08:38 UTC, DispatchCommit approved these changes
Can't comment on the `returnCachedClaims` part as I'm unfamiliar.

The rest of the code LGTM. I was going to try and compare the PR vs. Production performance for this, but I couldn't find any significant changes between performance graphs - and if there is a correlation that II'm not seeing, then more likely the overall network variations

![image](https://user-images.githubusercontent.com/45262335/110089491-0bdd3e00-7d4b-11eb-99da-3fcba7336560.png)

2021-03-08 00:45 UTC, infinite-persistence commented
`Update`
- Rebased/resolved conflict with master.

2021-03-08 17:51 UTC, seanyesmunt requested changes

2021-03-08 17:51 UTC, seanyesmunt commented on ui/component/channelContent/index.js
> +  doResolveUris: (uris) => dispatch(doResolveUris(uris)),
You need to forward the second argument here

2021-03-08 18:45 UTC, seanyesmunt commented on ui/component/channelContent/index.js
> +  doResolveUris: (uris) => dispatch(doResolveUris(uris)),
I pushed up a commit to do that

2021-03-08 18:46 UTC, seanyesmunt approved these changes

2021-03-08 19:05 UTC, merged