Fix autoplay not working in floating mode
lbryio/lbry-desktop pull request #5716
Opened 2021-03-19 15:06 UTC by infinite-persistence

## Issue
Closes #5000: [AutoPlay in Floating Player only works one time](https://github.com/lbryio/lbry-desktop/issues/5000)

## Changes
Factor out the code that queries the recommendation. It needs to be called in two places:
(1) `RecommendedContent` - need to cover the case of floating player + visit another video page.
(2) When video is floating and autoplayed the next video.

## Notes to reviewer
I think there's no need for `React.useCallback` anymore, but please double-check in case it was needed for something else.

2021-03-20 01:17 UTC, DispatchCommit reviewed
passes my lookover. Moving the logic out of the component seems like the right approach.

I'll leave this on sean to test and approve, but I don't see any potential edge cases that might cause issues in the logic.

2021-03-22 00:28 UTC, seanyesmunt requested changes
This looks  good. I would like to use `doFetchXXX` since  that is the pattern we use in other actions.

2021-03-22 00:28 UTC, seanyesmunt commented on ui/redux/actions/search.js
> +export const doGetRecommendedContent = (uri: string, mature: boolean) => (dispatch: Dispatch, getState: GetState) => {
`doFetchRecommendedContent`

2021-03-22 01:29 UTC, infinite-persistence commented
`-- Update --`
- Resolve conflict with master.
- Renamed: `doGetRecommendedContent` --> `doFetchRecommendedContent`

2021-04-02 17:34 UTC, seanyesmunt approved these changes

2021-04-02 18:35 UTC, merged