Feature Concept: recommended bar extra options for ease of discovery
lbryio/lbry-desktop pull request #5789
Opened 2021-03-28 14:25 UTC by saltrafael

## PR Checklist

Please check all that apply to this PR using "x":

- [X] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number:

## What is the current behavior?

Recommended bar could be improved to ease discovery in less clicks for the user

## What is the new behavior?

Added extra options for the recommended bar to allow for discovering more specific related content based on channel or tags, as shown in the pics:

![](https://i.postimg.cc/mkcTf0bz/image.png) 

![](https://i.postimg.cc/B6b0HdPY/image.png) ![](https://i.postimg.cc/RZThRxq4/image.png)

Comparison to that one popular Odysee Alternative from Web2.0:

![](https://i.postimg.cc/P57c0PC4/image.png)

The main difference being that the odysee alternative platform doesn't allow to filter tags

## Other information

This is a concept I've been testing on the weekend, there are some styling issues like if the channel name is too big you can't expand

2021-03-28 14:38 UTC, tzarebczan commented
Wow, this is a great start and good place to add improvements! For tag searches, are you using claim search?

2021-03-28 14:53 UTC, saltrafael commented
> Wow, this is a great start and good place to add improvements! For tag searches, are you using claim search?

Thanks! I just used a claim list discover with the selected tag as filter, so it's the same as going to each tags page, but faster and with less clicks

2021-03-28 19:55 UTC, tzarebczan commented
Yes, that's awesome! Maybe it can default to trending sort, and then let users change new/top also. 

This would be a great one to add soon also: https://github.com/lbryio/lbry-desktop/issues/5181 (there's some other search improvements in another PR too).

2021-03-29 12:20 UTC, saltrafael commented
> Yes, that's awesome! Maybe it can default to trending sort, and then let users change new/top also.
> 
> This would be a great one to add soon also: #5181 (there's some other search improvements in another PR too).

You mean like this?

![](https://i.postimg.cc/Sx4RjHMF/image.png) ![](https://i.postimg.cc/wMhHpTFt/image.png)

I had hid the filters so it doesn't look too different from before

2021-03-29 19:12 UTC, kauffj commented
this is a really cool idea but will need a style/UX pass from @seanyesmunt

2021-04-06 16:53 UTC, seanyesmunt requested changes
This is great! For now lets just start with one category "more from". Then we don't have to worry about expanding the section for more categories. Once those are removed I will push up a commit to do some styling to this new section.

Thank you for the PR! This will be great to have :slightly_smiling_face:

2021-04-06 16:53 UTC, seanyesmunt commented on ui/component/recommendedContent/view.jsx
> +  const [moreFrom, setMoreFrom] = React.useState(false);
for now lets just start with the "more from" toggle only.

2021-04-06 19:20 UTC, saltrafael commented
> This is great! For now lets just start with one category "more from". Then we don't have to worry about expanding the section for more categories. Once those are removed I will push up a commit to do some styling to this new section.
> 
> Thank you for the PR! This will be great to have 🙂

Done, and thanks for the feedback!!

2021-04-08 15:29 UTC, seanyesmunt commented
I added your commits to this branch so I could rebase
https://github.com/lbryio/lbry-desktop/pull/5847

Will merge once the build completes

2021-04-08 15:29 UTC, closed without merging