Fixes #5822 display of upload date and view count on smaller screens
lbryio/lbry-desktop pull request #5823
Opened 2021-04-04 02:51 UTC by lousando

## PR Checklist

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #5822 

## What is the current behavior?

Upload date and view count are displayed vertically on with little horizontal space.

![media_meta_below_1150px_before](https://user-images.githubusercontent.com/1214300/113497139-b4e79780-94b5-11eb-8c80-c521459b16ec.png)

## What is the new behavior?

Upload date and view count are displayed horizontally with more horizontal space.

![media_meta_below_1150px_after](https://user-images.githubusercontent.com/1214300/113497145-cb8dee80-94b5-11eb-890e-5807f89dc5b2.png)

2021-04-04 05:28 UTC, seanyesmunt requested changes
Thank you for the PR! This is great, I have just one comment.

2021-04-04 05:28 UTC, seanyesmunt commented on ui/scss/component/_file-render.scss
> +  // smaller screen
Please remove these comments

2021-04-04 20:14 UTC, lousando commented
Suggestions addressed.

2021-04-05 02:51 UTC, merged

2021-04-05 02:51 UTC, seanyesmunt commented
Merged! Can we show you some [appreciation](https://lbry.com/faq/appreciation)?