add pwa to lbry-desktop
lbryio/lbry-desktop pull request #6120
Opened 2021-05-25 17:45 UTC by mayeaux

## PR Checklist

Please check all that apply to this PR using "x":

- [ ] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-05-26 15:59 UTC, jessopb commented
Nice - I'm pretty sure the manifest will be for odysee and not lbry?

2021-05-26 16:02 UTC, kauffj commented
Yes, Odysee

2021-06-01 14:25 UTC, mayeaux commented on web/index.js
> +  maxage: 3600000, // set a cache time of one hour, helpful for mobile dev
I set this to make mobile development over ngrok easier, so it can cache the rather large JS file that is compiled (and also cache the fonts)

2021-06-01 14:59 UTC, kauffj commented
Image requirements can be bounced to @dejanbr.

2021-06-01 18:54 UTC, jessopb requested changes
Just a couple things

2021-06-01 18:54 UTC, jessopb commented on static/index-web.html
> +    <link rel="manifest" href="./public/pwa/manifest.json"/>
I'd like to inject these in index.js conditional on SITE_NAME
We can make a specific DESCRIPTION env if necessary.

2021-06-01 19:24 UTC, mayeaux commented
Btw, not quite ready for a merge, we got it up on a test server and realized it needs a touchup to fix a scope issue, should be a pretty quick fix though.

2021-06-03 19:46 UTC, jessopb approved these changes

2021-06-04 16:05 UTC, merged