Add watch later to hover action for last used playlist on popup
lbryio/lbry-desktop pull request #6274
Opened 2021-06-18 15:38 UTC by saltrafael

## PR Checklist

Please check all that apply to this PR using "x":

- [X] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [X] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: [WIP] for #6205

## What is the new behavior?

Switched around Watch Later to appear as a hover action on thumbnail:
![](https://i.postimg.cc/ZRttmNN4/image.png)
So the last used playlist can be at the popup menu, the reasoning is so the menu doesn't get too filled and makes both actions quicker, single click to watch later, first option on popup to most recent list:
![](https://i.postimg.cc/Kv96zwT9/image.png)

## Other information

But it still doesn't remember last used playlist choice, it's set to Favorites for now

2021-06-19 15:24 UTC, tzarebczan commented
Hmm, we'll have to think about this approach. YouTube does show it in both places.

2021-07-07 17:27 UTC, jessopb commented
I like this idea.
1: Favorites needs a different icon (probably a star)
2: Watch later button needs requiresAuth={IS_WEB} to redirect to account signin for those unauthorized
3. Got some styling suggestions...
https://github.com/lbryio/lbry-desktop/commit/fbb7a1875a33011e3bba02668c53204d2e0da755
4. I don't like the delete button - maybe the button on hover gets a label Add or Remove?

2021-07-07 17:31 UTC, jessopb requested changes

2021-07-07 17:31 UTC, jessopb commented on ui/component/claimPreview/view.jsx
> +                          icon={hasClaimInWatchLater ? ICONS.DELETE : ICONS.TIME}
requiresAuth={IS_WEB}

2021-07-07 17:31 UTC, jessopb commented on ui/component/claimPreviewTile/index.js
> +    claim: props.uri && makeSelectClaimForUri(props.uri)(state),
Just 
```
claim,
...
```

2021-07-07 17:31 UTC, jessopb commented on ui/component/claimPreviewTile/view.jsx
> +                    icon={hasClaimInWatchLater ? ICONS.DELETE : ICONS.TIME}
requiresAuth={IS_WEB}

2021-07-07 18:12 UTC, saltrafael commented
> 4. I don't like the delete button - maybe the button on hover gets a label Add or Remove?

[![image.png](https://i.postimg.cc/prCcHwbj/image.png)](https://postimg.cc/1Vgr0YzR) [![image.png](https://i.postimg.cc/fRp2D7F8/image.png)](https://postimg.cc/68VLhZBZ)

✔️ Like this ?

2021-07-07 18:47 UTC, jessopb commented
Not sure about remove - it's the trash can I don't like. 
Don't want to nitpick this. Tone down the text with styles if you can.
I'd kinda like to do this:

| ADDED?        | HOVER             | NOT HOVER |
| ------------------ | -------------------- | ------------------ |
| ADDED          | [clock][X]           | [clock[CHECK] |
| NOT ADDED | [clock][CHECK] | [clock] |

2021-07-07 20:12 UTC, jessopb commented
There's a star icon on master now if you rebase.

2021-07-08 13:39 UTC, saltrafael commented
how about this now?

[![image.png](https://i.postimg.cc/Nfp4p17N/image.png)](https://postimg.cc/Vd0nN0hM) [![image.png](https://i.postimg.cc/FH6xQN63/image.png)](https://postimg.cc/sMpWYdsg)
[![image.png](https://i.postimg.cc/cCTQkSYK/image.png)](https://postimg.cc/ctgg6PFZ) [![image.png](https://i.postimg.cc/Y9zgjHdX/image.png)](https://postimg.cc/mzhh60fM)

star icon:

[![image.png](https://i.postimg.cc/tCW1gy7F/image.png)](https://postimg.cc/2VjjHsQ5)

2021-07-08 14:56 UTC, jessopb commented
Nice. Thanks for bearing with us - I think we'll keep Watch Later in the menu as well as on the overlay (both).
Put favorites twice. And see how it goes. We will need to restyle the context menu so it doesn't break/overflow on mobile.

2021-07-08 17:28 UTC, saltrafael commented
👍
[![image.png](https://i.postimg.cc/tT2FWRCm/image.png)](https://postimg.cc/Kk3Ky2Tn)

2021-07-14 15:41 UTC, merged