fix issue of invalid aria-label values
lbryio/lbry-desktop pull request #6470
Opened 2021-07-13 20:22 UTC by btzr-io

## PR Checklist

Please check all that apply to this PR using "x":

- [ ] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number:

## What is the current behavior?

## What is the new behavior?

## Other information

2021-07-13 22:11 UTC, tzarebczan commented
I haven't filed this one, but I remember someone mention accessibility issues around the playlist feature - somewhere in the pop up menus. Can you take a peek?

2021-07-13 22:59 UTC, btzr-io commented
> 
> 
> I haven't filed this one, but I remember someone mention accessibility issues around the playlist feature - somewhere in the pop up menus. Can you take a peek?

What issues ? Need more info

2021-07-14 01:05 UTC, btzr-io commented
https://www.accessibility-developer-guide.com/

2021-07-15 03:30 UTC, btzr-io commented
Skip navigation feature: Useful for screen reader users ( tested with windows narrator )

![SkipNavigationLink](https://user-images.githubusercontent.com/14793624/125724726-b155ab38-095b-4069-95ca-cea17a2a8f45.gif)

2021-07-15 23:21 UTC, btzr-io commented
New aria-label format for claim preview links:
This includes additional information of the claim.

```
%title% by %channelTitle%, %mediaDuration%
```

Screen reader
```
Narrator: "Link Awesome Cats! by Animals, one minute (00:10:00)"
```
### Todo

- [ ] Include more info ? ( release date, file type, price ) ?

2021-07-16 07:31 UTC, btzr-io commented
Waiting for review or feedback before any more changes.

2021-07-16 07:37 UTC, btzr-io commented on ui/component/header/view.jsx
> +const SkipNavigationButton = () => {
Should I move this component to is own file ?

2021-07-22 02:33 UTC, jessopb approved these changes

2021-07-23 07:24 UTC, btzr-io commented on ui/scss/component/_button.scss
> +    background-color: var(--color-button-alt-bg);
Fix #6503

2021-07-29 03:40 UTC, infinite-persistence commented
@btzr-io , can you make one final rebase to resolve the conflicts? Will get this in soon.

2021-07-29 07:13 UTC, infinite-persistence requested changes
One more minor fix needed

2021-07-29 07:13 UTC, infinite-persistence commented on ui/util/formatAriaLabel.js
> +  return ariaLabelData;
I think we forgot to remove the `+=`?

<img src="https://user-images.githubusercontent.com/64950861/127447038-08f215ba-663f-4670-bdab-2736eca4215f.png" width="400">

2021-07-29 20:43 UTC, btzr-io commented
Changelog update: #6735

2021-07-30 01:39 UTC, merged