Issue/7152
lbryio/lbry-desktop pull request #7214
Opened 2021-10-01 20:51 UTC by bluerabbit001

Issue Number:  7152

Added download progress and cancel features.

2021-10-02 06:14 UTC, jessopb requested changes
The look and feel is great and the code is clean and readable.
Just pointed out some DRY reuse opportunities a couple bugs and codebase style consistency preferences.

2021-10-02 06:14 UTC, jessopb commented on ui/component/downloadProgress/view.jsx
> +    const item = props.downloadList[key];
something weird happens here that crashes the app when I play a video.
"cannot read status of null"
redux devtools (which has a bug that sometimes doesn't load unless you `yarn dev` and wait for the app to finish before opening devtools) tells me initial state byOutpoint is { <outpoint>: null } until file_list fetch comes back.

2021-10-05 20:17 UTC, jessopb requested changes
Changes look better, but:
Card overlay download status styling is invisible on dark mode
Download then Playing another created a condition where a download was stuck - and X-ing the download killed the playing video.

2021-10-07 16:00 UTC, jessopb commented
![image](https://user-images.githubusercontent.com/36554050/136421355-45ba39b2-12f7-4e20-8af2-dae6988961fd.png)
Playing a video and then playing another video causes indicator to get stuck at `Infinity minutes NaN`

2021-10-08 17:48 UTC, bluerabbit001 commented
> I think it might be better to show download progress for all videos downloading whether playing or not. But perhaps disable the 'x' if currently playing - maybe indicate currently playing as well.

It is good idea and I implemented it according to your logic.

2021-10-08 23:32 UTC, bluerabbit001 commented
> Still getting buggy/stuck display with infinity and NaN when clicking from play to play. Not sure what changed.

clear cache and try again

2021-10-08 23:32 UTC, bluerabbit001 commented
> Check to see if on your branch, the side menu works while on a player page. It seems to work on master, so might be a rebase issue.

clear cache and try again.

2021-10-08 23:52 UTC, jessopb commented
cleared electron application info, cleared the dist folder, checked that most recent branch is `update css` made sure I didn't have other repos linked locally. Your new bouncing notification button shows up. Playing videos do not show up.

2021-11-15 13:50 UTC, jessopb commented
closed in favor of rebase

2021-11-15 13:50 UTC, closed without merging