fix hover style for char count field
lbryio/lbry-desktop pull request #7620
Opened 2022-06-20 22:02 UTC by ByronEricPerez

## Fixes

Issue Number: https://github.com/lbryio/lbry-desktop/issues/7564

## What is the current behavior?

## What is the new behavior?

## Other information

## PR Checklist

<details><summary>Toggle...</summary>

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [ ] I added a line describing my change to CHANGELOG.md
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

</details>

2022-06-28 12:52 UTC, ByronEricPerez commented
Hi @jessopb  all good with this, do you need me to change something?

2022-06-28 19:30 UTC, jessopb commented
I think this would be cleaner if it weren't class "button--file-action". It's not completely clear what file-action is, but this is a comment action or something. I think it deserves its own class. button--comment-icons, perhaps.

2022-06-30 20:01 UTC, ByronEricPerez commented
Hello, @jessopb  I have already sent the changes, is this ok?

2022-07-01 14:25 UTC, jessopb commented
@ByronEricPerez I think it just needs a clean class that takes the place of button--file-actions because it's not a "file-action".

2022-07-05 13:09 UTC, ByronEricPerez commented
Hello @jessopb , it is not entirely clear to me, would it be to rename the class?

2022-07-05 15:28 UTC, jessopb requested changes

2022-07-05 15:28 UTC, jessopb commented on ui/component/common/form-components/form-field.jsx
> +                    className="button--file-action button--comment-icons"
this should not need button--file-action
One class should be sufficient to specify what this should look like.
button--comment-icons should contain all that it needs.

2022-07-05 15:28 UTC, jessopb commented on ui/scss/component/_button.scss
> +.button--comment-icons {
I know it's not super D.R.Y. but I would duplicate the button--file-action class contents here.

Then we can get rid of commented out lines.

2022-07-05 19:37 UTC, ByronEricPerez commented
Hi @jessopb , would that be ok?

2022-07-05 22:02 UTC, jessopb reviewed
Yeah, this is better. Just a couple more comments.

2022-07-05 22:02 UTC, jessopb commented on ui/scss/component/_button.scss
> +  padding: 5px;
There's a duplicate padding: line here. Also, whenever possible, we're trying to use vars for spacing, as above. Does one of those work?

2022-07-07 17:43 UTC, jessopb approved these changes
This looks good!

2022-07-07 20:55 UTC, merged